name: NFT Catalog Integration Tests

on: pull_request

jobs:
    tests:
        env:
            CATALOG_TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.CATALOG_TESTNET_ACCOUNT_PRIVATE_KEY }}
            EXAMPLENFT_TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.EXAMPLENFT_TESTNET_ACCOUNT_PRIVATE_KEY }}
            EXAMPLENFT_TESTNET_HOLDER_ACCOUNT_PRIVATE_KEY: ${{ secrets.EXAMPLENFT_TESTNET_HOLDER_ACCOUNT_PRIVATE_KEY }}
        runs-on: ubuntu-latest
        steps:
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install FLOW CLI
              run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

            - name: Update PATH
              run: echo "/root/.local/bin" >> $GITHUB_PATH

            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install

            - name: Install UI Dependencies
              run: npm run install-ui

            - name: Run Cadence Tests
              if: always()
              run: npm test

            - name: Run E2E Cypress Tests
              if: always()
              run: npm run e2e
